// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"


// State
UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Standing)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Falling)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Lying)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead)


// Combat State
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Attack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Evade)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Guard)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Sprint)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Hit)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Parry)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_PerfectParry)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_LockOn)


// Input
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_InputInstance)

// HitType
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Head)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Right)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Left)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Flying)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_KnockDown)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Body)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Dicing)


// KnockbackType
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knockback_Pull)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knockback_PullToHitter)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knockback_Push)

// EC 
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EC_Damage)

//GE
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Buff_Immortal)


// Regen 
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Regen_Stop_Health)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Regen_Stop_Stamina)

