syntax = "proto3";

enum PacketType
{
	PT_NONE = 0;
	PT_CS_LOGIN = 1;
	PT_SC_LOGIN = 2;
	PT_CS_MATCH = 3;
	PT_SC_MATCH = 4;
	PT_DS_DEDI = 5;
	PT_SD_DEDIExit = 6;
	PT_MAX =7;
}

enum PacketErrorCode
{
	Fail = 0;
	Success =1;
}

message AccountData
{
	string ID = 1;
	string Password = 2;
}

message CS_Packet_Login
{
	string UserId = 1;
    string Password = 2;
}
message SC_Packet_Login
{
	AccountData AccountData = 1;
	bool IsAccountCreated =2;
}

message CS_Packet_Match
{
	string UserId = 1;
}
message SC_Packet_Match
{
	string DedicateServerIP = 1; 
	string Port =2;
}

message DS_Packet_Dedi
{
	string BatcherID = 1;
	string Port = 2;
}

message SD_Packet_DediExit
{
	string BatcherID = 1;
	string Port = 2;
}