;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Project/TableData/GameplayAbilityTagTable.GameplayAbilityTagTable
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="EC.Damage",DevComment="")
+GameplayTagList=(Tag="Event.GameProcess.PlayerState_BothReady",DevComment="")
+GameplayTagList=(Tag="Event.GameProcess.Possess",DevComment="")
+GameplayTagList=(Tag="Event.Server.Login",DevComment="")
+GameplayTagList=(Tag="Event.Server.Match",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Immortal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Parry",DevComment="")

