;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Project/TableData/GameplayAbilityTagTable.GameplayAbilityTagTable
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Skill1",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill2",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill3",DevComment="")
+GameplayTagList=(Tag="Cost.CoolTime",DevComment="")
+GameplayTagList=(Tag="Cost.CurrentHealth",DevComment="")
+GameplayTagList=(Tag="Cost.CurrentStamina",DevComment="")
+GameplayTagList=(Tag="EC.Damage",DevComment="")
+GameplayTagList=(Tag="Event.GameProcess.PlayerState_BothReady",DevComment="")
+GameplayTagList=(Tag="Event.GameProcess.Possess",DevComment="")
+GameplayTagList=(Tag="Event.HUDInitialized",DevComment="")
+GameplayTagList=(Tag="Event.Server.Login",DevComment="")
+GameplayTagList=(Tag="Event.Server.Match",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Burn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DeathCircle",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Immortal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Parry",DevComment="")
+GameplayTagList=(Tag="GE.Debuff.Burn",DevComment="")
+GameplayTagList=(Tag="Item.UseItem",DevComment="")
+GameplayTagList=(Tag="Level.BattleMap",DevComment="")
+GameplayTagList=(Tag="Level.LoginMap",DevComment="")
+GameplayTagList=(Tag="Phase.Phase1",DevComment="")
+GameplayTagList=(Tag="Phase.Phase2",DevComment="")
+GameplayTagList=(Tag="Phase.Phase3",DevComment="")
+GameplayTagList=(Tag="Phase.Phase4",DevComment="")
+GameplayTagList=(Tag="Phase.Phase5",DevComment="")
+GameplayTagList=(Tag="Phase.Phase6",DevComment="")
+GameplayTagList=(Tag="Phase.Phase7",DevComment="")
+GameplayTagList=(Tag="Phase.Phase8",DevComment="")
+GameplayTagList=(Tag="Phase.Phase9",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill2",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase1",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase2",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase3",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase4",DevComment="")
+GameplayTagList=(Tag="Stat.CriticalChance",DevComment="")
+GameplayTagList=(Tag="Stat.CriticalDamage",DevComment="")
+GameplayTagList=(Tag="Stat.Defense",DevComment="")
+GameplayTagList=(Tag="Stat.HealthRegen",DevComment="")
+GameplayTagList=(Tag="Stat.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Stat.MaxStamina",DevComment="")
+GameplayTagList=(Tag="Stat.StaminaRegen",DevComment="")
+GameplayTagList=(Tag="UI.HUDBase",DevComment="")
+GameplayTagList=(Tag="UI.PopUp.ItemSplit",DevComment="")
+GameplayTagList=(Tag="UI.StatusBase",DevComment="")

