;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Project/TableData/GameplayAbilityTagTable.GameplayAbilityTagTable
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Skill1",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill2",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill3",DevComment="")
+GameplayTagList=(Tag="Cost.CoolTime",DevComment="")
+GameplayTagList=(Tag="Cost.CurrentHealth",DevComment="")
+GameplayTagList=(Tag="Cost.CurrentStamina",DevComment="")
+GameplayTagList=(Tag="EC.Damage",DevComment="")
+GameplayTagList=(Tag="Event.GameProcess.PlayerState_BothReady",DevComment="")
+GameplayTagList=(Tag="Event.GameProcess.Possess",DevComment="")
+GameplayTagList=(Tag="Event.HUDInitialized",DevComment="")
+GameplayTagList=(Tag="Event.Server.Login",DevComment="")
+GameplayTagList=(Tag="Event.Server.Match",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Burn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Immortal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Parry",DevComment="")
+GameplayTagList=(Tag="GE.Debuff.Burn",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill2",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase1",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase2",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase3",DevComment="")
+GameplayTagList=(Tag="Skill.KatanaSkill1.Phase4",DevComment="")
+GameplayTagList=(Tag="UI.HUDBase",DevComment="")
+GameplayTagList=(Tag="UI.PopUp.ItemSplit",DevComment="")
+GameplayTagList=(Tag="UI.StatusBase",DevComment="")

